### ISSUE TITLE
TBGRAImageList don't work with TImageIndexPropertyEditor

### ISSUE THREAD

**Issue by fluisgirardi** [bgrabitmap/bgracontrols#20]
TBGRAImageList don't work with TImageIndexPropertyEditor. When it is used on objects that has this property handling some property, the list is empty, only the first one is painted with one of picture of list.

Only in GKT2. QT is Fine. I don't know the behavior in other systems/platforms. 

To reproduce this:

1) Put a TBGRAimageList on a project and configure it (image size and put some images on Image List)
2) Then put a TPopupMenu and link it with previous created TBGRAImageList. 
3) Edit the previous created TPopupMenu and Insert a MenuItem
4) On created MenuItem, look at the property ImageIndex. Click on it and  combobox will appear. Look at the Itens

**Comment by lainz** [comment]
Hi, BGRAImageList is beign deprecated, and is not removed only because maybe people already using it can broke his projects.

The problem we have is that Lazarus in trunk is developing an High DPI Image List, that broken completely our component.

I don't know how to fix it, so I just removed the alpha support in one of the latest releases of BGRAControls.

Please don't use this component, I will find a way to mark it as deprecated.

**Comment by fluisgirardi** [comment]
Thanks!
