### ISSUE TITLE
Add Glyph support in Buttons

### ISSUE THREAD

**Issue by lainz** [bgrabitmap/bgracontrols#64]
The buttons that currently doesn't have glyph: TBCImageButton, TBCMDButton, TBCMaterialDesignButton.

Adding glyph to the other buttons doesn't have sense, but it can be discussed.

**Comment by lainz** [comment]
Maybe waiting for the SVG ImageList stuff first.

**Comment by circular17** [comment]
Yeah. Also it could be good to add a zoom factor, because on Retina, you need to have double size, but needs to be rendered at 50% of the size. In LazPaint there are a 2 buttons that would be improved with that, but that's not much difference honestly. There is no need to rush for that.

I guess when using an ImageList, it doesn't get the image with Retina scaling either.

Though it is true that we don't really need that if we get the vectorial image list.

**Comment by lainz** [comment]
Ok, yes the retina support is a thing to take into consideration as well.

**Comment by lainz** [comment]
I think I'm closing this, since we have the retina glyph working in BCButton. If one wants an image button now can use the SVG Button as well, so no need to improve the old controls with glyph in my opinion.
