### ISSUE TITLE
 BCMDButton improvements

### ISSUE THREAD

**Issue by vagneralmeida** [bgrabitmap/bgracontrols#99]
Hi!
I added the following properties:
- KindAnchor
- KindColor
- KindWidth
How do I send the source for you to test?

**Comment by lainz** [comment]
Hi, what you need to do is to fork the repository, at the top right there is a button to do that.

Then switch to dev-branch, that has the most up to date source code.

Then add your changes, make a pull request so we can see your changes, if all is ok we can merge it automatically.

Please add some description of what your changes does, since is not too much clear only with the property names.

Thanks.

**Comment by lainz** [comment]
Hmm that sounds complex right? Well you can as well attach the sources here, and we can check that.

**Comment by vagneralmeida** [comment]
153 / 5000
Resultados de tradução
I'm making some more improvements.
As soon as I finish everything I will send following your tip.
If I have difficulties I will contact you for help.

**Comment by lainz** [comment]
Sure. Thanks.
